[package]
name = "minifi_pgp"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
minifi-native = { path = "../minifi-native" }
strum_macros = "0.27.2"
strum = "0.27.2"
pgp = "0.18.0"
rand = "0.8.5"

[dev-dependencies]
minifi-native = { path = "../minifi-native" }
