[package]
name = "minifi_pgp"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
minifi_native = { path = "../../minifi_native" }
strum_macros = "0.27.2"
strum = "0.27.2"
pgp = "0.19.0"
rand = "0.8.5" # pgp 0.19.0 doesnt support >= 0.9 rand yet

