[package]
name = "behave_tester"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3.3"
minifi_pgp = { path = "../minifi_pgp" }
rust_reference_extension = { path = "../rust_reference_extension" }

[lints.rust]
unused_crate_dependencies = "allow"